name: Build and Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: cmake -S . -B build && cmake --build build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: cmake -S . -B build && cmake --build build
      - name: Test
        run: python3 -m pytest
