name: Build and Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: arch-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cmake -S . -B build && cmake --build build
      - name: Test
        run: pytest
